### ISSUE TITLE
Runtime Error: Type Error (while attempting to look up get_lan_ip) [line 452] (remote)

### ISSUE THREAD

**Issue by 90th** [rocketorbit/rocShell#15]
―# re 172.16.10.4 22
[###################################]==[ 100% ]
Searching required library init.so => found!
Starting attack... failed!
No active user found.
Starting attack... failed!
No active root user found.
Starting attack... failed!
No active root user found.
Starting attack... failed!
No active user found.
Starting attack... failed!
No active user found.

Starting attack...success!
Computer obtained with credentials from user: root
Starting attack... failed!
Insufficient amount of port forward towards the target.
Starting attack... failed!
No active root user found.
Searching required library kernel_module.so => found!
Starting attack... failed!
No active user found.
Starting attack... failed!
No active user found.
Starting attack... failed!
No active root user found.
Starting attack... failed!
Insufficient amount of port forward towards the target.
1.  root:computer  0x3C81EE58  codecflu  
    
Select> 1
Runtime Error: Type Error (while attempting to look up get_lan_ip) [line 452]

(I've also ran into an error on line 503 -     if lanPort.is_closed then  )
for some reason if the port is closed on a lan server it fail

―# nmap 192.168.20.2
Local Machine at 192.168.20.2
Runtime Error: Key Not Found: 'is_closed' not found in map [line 503]

**Comment by mahocitrus** [comment]
should be fixed.
